image: gitlab-registry.mpcdf.mpg.de/mpcdf/module-image

# trigger a notification for the launchpad repo to update the Dockerfile
notify-launchpad:
  only:
    - refactoring
  script:
    - module load git
    - git clone https://oauth2:${DEPLOYTOKEN}@gitlab.mpcdf.mpg.de/MPIBP-Hummer/glycoshield-md-binder-launchpad.git
    - cd glycoshield-md-binder-launchpad
    - sed -i "s/.*TRIGGERED_FROM_MAIN_REPO.*/    echo TRIGGERED_FROM_MAIN_REPO $CI_COMMIT_SHORT_SHA >.rebuild.log/" Dockerfile
    - |
      CHANGED=0
      git diff-index --quiet HEAD || CHANGED=1
      if [ $CHANGED -eq 0 ]
      then
        echo "all files unchanged, nothing to commit"
      else
        git config user.email "noreply@mpcdf.mpg.de"
        git config user.name "Automated Repository Update"
        git commit -a -m "GlycoSHIELD-MD $CI_COMMIT_SHORT_SHA"
        git push
      fi

pages:
    stage: deploy
    tags:
        - docker
    script:
        - >
          cat <<EOF >public/index.html
<!DOCTYPE html>
<html>
<body>
<h1>Directly below we use the iframe</h1>
<iframe src="https://notebooks.mpcdf.mpg.de/binder/v2/git/https%3A%2F%2Fgitlab.mpcdf.mpg.de%2FMPIBP-Hummer%2Fglycoshield-md-binder-launchpad.git/HEAD?urlpath=streamlit" title="GlycoSHIELD web application"></iframe>
</body>
</html>
          EOF
    artifacts:
        paths:
            - public
    only:
        - develop

