name: glycoshield
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - mdanalysis
  - gromacs=2021.3
  - pocl
  - nglview
  - pip
  - pip:
    - -e .
