# Conda environment recipe for GlycoSHIELD, to be used locally or with Binder
name: glycoshield
channels:
  - conda-forge
  - bioconda
dependencies:
  # base packages for command line usage
  - python=3.8
  - pip
  - mkl
  - blas=*=*mkl
  - numpy
  - scipy
  - matplotlib=3.4.3
  - font-ttf-ubuntu
  - mdanalysis
  - gromacs=2021.3
  # support for interactive jupyter notebooks
  - pocl
  - jupyterlab
  - nglview
  - ipywidgets
  # - voila
  # support for streamlit, the following combination of click and streamlit appears to work (to be checked in the future)
  - click=8.0.4
  - streamlit=1.8.0
  - jupyter-server-proxy
  # support for documentation creation
  - sphinx
  # finally, install the glycan data and the present package in editable mode
  - pip:
    #- zenodo-get
    - py3Dmol
    - stmol
    - sphinx-rtd-theme
    - git+https://gitlab.mpcdf.mpg.de/khr/jupyter-streamlit-proxy.git
    - -e ../glycoshield-data-download-helper/
    - -e ../
